workflows:
  reyyy-ai-build:
    name: REYYY AI Build
    environment:
      node: 20.0.0
    scripts:
      - cd ReyyyAI
      - npm install
      - npm install -g eas-cli
      - EXPO_TOKEN=C4UIskBKdggk8X_7pvhy8_b4PBXpweBKU1NFu9gQ eas build --platform android --profile preview
    artifacts:
      - ReyyyAI/build/**/*.apk
