workflows:
  reyyy-ai-build:
    name: REYYY AI Build
    environment:
      node: 20.0.0
    scripts:
      - name: Install dependencies
        script: |
          cd ReyyyAI
          npm install
      - name: Install EAS CLI
        script: |
          cd ReyyyAI
          npm install -g eas-cli
      - name: Build APK
        script: |
          cd ReyyyAI
          EXPO_TOKEN=C4UIskBKdggk8X_7pvhy8_b4PBXpweBKU1NFu9gQ eas build --platform android --profile preview
    artifacts:
      - ReyyyAI/build/**/*.apk
