export const COMMANDS = [
  { name: '/proxy status', description: 'Lihat status semua proxy', category: 'proxy' },
  { name: '/proxy start [name]', description: 'Nyalakan proxy', category: 'proxy' },
  { name: '/proxy stop [name]', description: 'Matikan proxy', category: 'proxy' },
  { name: '/proxy restart [name]', description: 'Restart proxy', category: 'proxy' },
  { name: '/proxy list', description: 'Daftar proxy terinstall', category: 'proxy' },
  { name: '/proxy info [name]', description: 'Detail proxy', category: 'proxy' },
  { name: '/proxy logs [name]', description: 'Live log proxy', category: 'proxy' },
  { name: '/keys', description: 'Lihat semua API key (masked)', category: 'keys' },
  { name: '/keys add [key]', description: 'Tambah API key baru', category: 'keys' },
  { name: '/keys remove [id]', description: 'Hapus API key', category: 'keys' },
  { name: '/keys test [id]', description: 'Test validasi key', category: 'keys' },
  { name: '/keys info [id]', description: 'Detail key', category: 'keys' },
  { name: '/keys rename [id] [name]', description: 'Rename key', category: 'keys' },
  { name: '/keys toggle [id]', description: 'Aktif/nonaktifkan key', category: 'keys' },
  { name: '/models', description: 'Lihat semua model', category: 'models' },
  { name: '/models add', description: 'Tambah model baru', category: 'models' },
  { name: '/models remove [name]', description: 'Hapus model', category: 'models' },
  { name: '/models info [name]', description: 'Detail model', category: 'models' },
  { name: '/models test [name]', description: 'Test model', category: 'models' },
  { name: '/models use [name]', description: 'Set model aktif', category: 'models' },
  { name: '/models default [name]', description: 'Set default model', category: 'models' },
  { name: '/tier', description: 'Lihat tier list', category: 'tier' },
  { name: '/tier [category]', description: 'Tier per kategori', category: 'tier' },
  { name: '/tier set [model] [tier]', description: 'Pindahkan model ke tier', category: 'tier' },
  { name: '/tier export', description: 'Export tier list', category: 'tier' },
  { name: '/tier import [file]', description: 'Import tier list', category: 'tier' },
  { name: '/skills', description: 'Lihat semua skill', category: 'skills' },
  { name: '/skills [model]', description: 'Skill per model', category: 'skills' },
  { name: '/skills install [m] [n]', description: 'Install skill', category: 'skills' },
  { name: '/skills install file', description: 'Install dari file .md', category: 'skills' },
  { name: '/skills install url [url]', description: 'Install dari URL', category: 'skills' },
  { name: '/skills remove [m] [n]', description: 'Hapus skill', category: 'skills' },
  { name: '/skills info [m] [n]', description: 'Detail skill', category: 'skills' },
  { name: '/skills use [m] [n]', description: 'Aktifkan skill', category: 'skills' },
  { name: '/skills deactivate', description: 'Nonaktifkan skill', category: 'skills' },
  { name: '/backup', description: 'Backup semua data', category: 'backup' },
  { name: '/backup --type [t]', description: 'Backup tipe spesifik', category: 'backup' },
  { name: '/backup auto on/off', description: 'Auto-backup', category: 'backup' },
  { name: '/backup list', description: 'Daftar backup', category: 'backup' },
  { name: '/backup clean', description: 'Hapus backup >30 hari', category: 'backup' },
  { name: '/restore', description: 'Pulihkan dari backup', category: 'backup' },
  { name: '/restore --preview [path]', description: 'Preview backup', category: 'backup' },
  { name: '/bugs', description: 'Error log hari ini', category: 'bugs' },
  { name: '/bugs all', description: 'Semua error log', category: 'bugs' },
  { name: '/bugs stats', description: 'Statistik auto-fix', category: 'bugs' },
  { name: '/bugs detail [id]', description: 'Detail error', category: 'bugs' },
  { name: '/bugs fix [id]', description: 'Manual fix error', category: 'bugs' },
  { name: '/bugs fix all', description: 'Fix semua unresolved', category: 'bugs' },
  { name: '/bugs clear', description: 'Clear error log', category: 'bugs' },
  { name: '/bugs export', description: 'Export error log', category: 'bugs' },
  { name: '/status', description: 'Status sistem lengkap', category: 'status' },
  { name: '/health', description: 'Cek provider + proxy', category: 'status' },
  { name: '/health deep', description: 'Deep health check', category: 'status' },
  { name: '/tokens', description: 'Penggunaan token', category: 'status' },
  { name: '/analytics', description: 'Dashboard penggunaan', category: 'status' },
  { name: '/network', description: 'Cek koneksi', category: 'status' },
  { name: '/chat new', description: 'Buat chat baru', category: 'chat' },
  { name: '/chat list', description: 'Daftar chat', category: 'chat' },
  { name: '/chat search [kw]', description: 'Cari chat', category: 'chat' },
  { name: '/chat pin [id]', description: 'Pin chat', category: 'chat' },
  { name: '/chat label [id] [l]', description: 'Label chat', category: 'chat' },
  { name: '/chat delete [id]', description: 'Hapus chat', category: 'chat' },
  { name: '/chat export [id]', description: 'Export chat', category: 'chat' },
  { name: '/chat clear', description: 'Hapus semua chat', category: 'chat' },
  { name: '/templates', description: 'Lihat template', category: 'template' },
  { name: '/template save [n] [p]', description: 'Simpan template', category: 'template' },
  { name: '/template use [n]', description: 'Pakai template', category: 'template' },
  { name: '/template delete [n]', description: 'Hapus template', category: 'template' },
  { name: '/rules', description: 'Lihat rules', category: 'rules' },
  { name: '/rules add [c] [a]', description: 'Tambah rule', category: 'rules' },
  { name: '/rules remove [id]', description: 'Hapus rule', category: 'rules' },
  { name: '/rules toggle [id]', description: 'Aktif/nonaktifkan rule', category: 'rules' },
  { name: '/settings', description: 'Buka Settings', category: 'system' },
  { name: '/theme [dark/light]', description: 'Ganti tema', category: 'system' },
  { name: '/accent [color]', description: 'Ganti warna aksen', category: 'system' },
  { name: '/clear', description: 'Bersihkan terminal', category: 'system' },
  { name: '/help', description: 'Bantuan', category: 'system' },
  { name: '/help [cmd]', description: 'Bantuan command', category: 'system' },
  { name: '/about', description: 'Info aplikasi', category: 'system' },
  { name: '/version', description: 'Versi aplikasi', category: 'system' },
  { name: '/changelog', description: 'Changelog', category: 'system' },
  { name: '/restart', description: 'Restart aplikasi', category: 'system' },
];